### ISSUE TITLE
List validator treating obsolete accessions as valid

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#1771]
Expected Behavior 
--------------------------------------------------------------------------

Encountered this in sweetpotatobase-test. Accession 'Hatteras' was obsoleted, then later used in a list and pedigree upload. Lists with 'Hatteras' pass validation, but pedigree upload fails (as it should) because it is obsoleted.

For Bugs:
---------

### Environment 

sweetpotatobase.org

**Comment by lukasmueller** [comment]
In the code, it looks like the accession validator checks for is_obsolete... Has this been fixed already or is there another underlying problem?

**Comment by lukasmueller** [comment]
I find that not all validators (such as Cross) check is_obsolete... maybe those should be fixed as well.

**Comment by bellerbrock** [comment]
@lukasmueller It's still happening, and still a mystery what's causing it . The relevant stock entry for Hatteras is obsolete:
![hatteras](https://user-images.githubusercontent.com/11297346/38509418-d45a41f2-3bef-11e8-9b8a-9d9c0fe3c9c3.png)
I'll take a closer look

**Comment by bellerbrock** [comment]
Ah, I see what's going on. Hatteras was also added as a synonym for Hatteras_G1, that's why it's still being accepted as valid in a list.

I'm not sure what the best solution is to this, but if synonyms are valid in a list we should also make sure they're valid (or at least noticed and returned with an informative error) in searches and other uploads
