### ISSUE TITLE
Certain VCF downloads have missing CHROM and POS fields

### ISSUE THREAD

**Issue by lukasmueller** [solgenomics/sgn#3765]
Expected Behavior 
--------------------------------------------------------------------------
The download functionality https://cassavabase.org//breeders/download_gbs_action?format=accession_ids&ids=39680 seems to have lost the #CHROM and POS attribute. There is only ID. Is that a new vcf variant or did that get lost in some update?

Other downloads work fine (for example from the Wizard or downloading page).

For Bugs:
---------

**Comment by lukasmueller** [comment]
fixed via 67c1eb11a45302ac32a3338f6cb8af3f877538d4.

**Comment by ClayBirkett** [comment]
The changes you made are in _compute_from_parents subroutine. Do you know how to fix the problem when the data is not from parents? The GWAS is still broken

**Comment by ClayBirkett** [comment]
fixed by https://github.com/solgenomics/sgn/pull/3847
