### ISSUE TITLE
Deleted/obsolete accessions still show up in accession search and pass validation when part of a list

### ISSUE THREAD

**Issue by bellerbrock** [solgenomics/sgn#539]

**Comment by lukasmueller** [comment]
List accession validation fixed in 22876bb3a8ea59d0aea52ff697cd7fea632eb599. List tests still pass: t/unit_fixture/CXGN/List.t and t/selenium2/01_list/list.t (however, list validation has poor test coverage).

**Comment by lukasmueller** [comment]
Stock search fixed in acf5c22b6b2cc3fc2cd3764eabdba86fe14e8f3a. Need to improve test coverage for this. May be good to add an option on the stock search with a checkbox 'search obsoleted stocks' so that they can still be found. Another good option would be to have a button on the stock detail page of an obsolete stock that would do a hard delete.

**Comment by bellerbrock** [comment]
a hard delete option seems important - obsolete accession no longer show up in the stock search and list validation, but they still show up in the fuzzy search, and they prevent new accessions from being added with the same name.
